In [1]:
import numpy as np


In [15]:
a = np.array([1,2,3],dtype = np.int32)
print(a)

[1 2 3]


In [3]:
b = np.array([[1.0,2.6,7.9], [4.1,5.2,6.3]])
print(b)

[[1.  2.6 7.9]
 [4.1 5.2 6.3]]


In [7]:
# Dimension
a.ndim

1

In [8]:
b. ndim


2

In [9]:
# Shapes
a.shape

(3,)

In [10]:
b.shape


(2, 3)

In [11]:
# size
a.size

3

In [12]:
b.size

6

In [16]:
# itemsize
a.itemsize

4

In [17]:
b.itemsize

8

In [18]:
# total size
a.size * a.itemsize

12