Accesinng/Changing specific element .


In [2]:
import numpy as np


In [26]:
a = np.array([[1, 2, 3, 4, 5,6,8,5],[6,7,8,9,10,11,12,13]])
print(a)

[[ 1  2  3  4  5  6  8  5]
 [ 6  7  8  9 10 11 12 13]]


In [13]:
a.shape

(2, 8)

In [14]:
#Get specifice element. [r,c]
a[1,4]

np.int64(10)

In [15]:
# Negative Indexing . Last column will be -1
a[1,-2]

np.int64(12)

In [16]:
# Get a specific row . [r, :]]
a[1, :]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [17]:
# Get a specific column . [:, c]]
a[:, 3]

array([4, 9])

In [18]:
# Sllicing of array . [start:stop:jump]
# Start from index : stop before this index : jump
a[1, 1:4:]

array([7, 8, 9])

In [19]:
a[0, 1:4:]

array([2, 3, 4])

In [21]:
a[1, 1:-6:2]

array([7])

In [22]:
a[1,1:-1:2]

array([ 7,  9, 11])

Altering Data


In [25]:
a[0,7] = 10
print(a)

[[ 1  2  3  4  5  6  8 10]
 [ 6  7  8  9 10 11 12 13]]


In [26]:
a[:,-6] = 69
print(a)

[[ 1  2 69  4  5  6  8 10]
 [ 6  7 69  9 10 11 12 13]]


In [28]:
a[:,-7]= [6,9]
print(a)

[[ 1  6 69  4  5  6  8 10]
 [ 6  9 69  9 10 11 12 13]]


In [8]:
b = np.array([[[1,2],[4,5]],[[6,7],[8,9]]])
print(b)

[[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]


In [11]:
#Getting  specific Element 
b[0,1,1]

np.int64(5)

Initializing Different types of arrays

In [18]:
#All 0s Matrix 
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#Any other nummbers
np.full((2,2),34,dtype= 'float32')

array([[34., 34.],
       [34., 34.]], dtype=float32)

In [34]:
# fulllike() : It creates a new array with the same shape and data type as an existing array, but fills it with a value you specify.
# syntax : np.fulllike(existing array , fill_value)
c = np.full_like(b,3)

In [3]:
f = np.full((3,2),6)
f

array([[6, 6],
       [6, 6],
       [6, 6]])

In [35]:
# Random decimal numbers 
c= np.random.rand(4,2)
print (c)

[[0.09686426 0.81447617]
 [0.52930495 0.78120815]
 [0.85731387 0.3837052 ]
 [0.92767134 0.53024094]]


In [38]:
# Random Integer Value
np.random.randint(4,7,size=(3,3))

array([[6, 6, 4],
       [6, 6, 6],
       [4, 5, 6]], dtype=int32)

In [40]:
# Identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
x = np.array([1,2])

In [47]:
d = np.random.random_sample(x.shape)
print(d)

[0.55672416 0.33073088]


In [48]:
#Repeat 
# Syntax = np.repeat(array,repeats,axis=0)
np.repeat(x,2,axis=0)

array([1, 1, 2, 2])

In [6]:
I = np.identity((3))
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])