Accesinng/Changing specific element .


In [1]:
import numpy as np


In [12]:
a = np.array([[1, 2, 3, 4, 5,6,8,5],[6,7,8,9,10,11,12,13]])
print(a)

[[ 1  2  3  4  5  6  8  5]
 [ 6  7  8  9 10 11 12 13]]


In [13]:
a.shape

(2, 8)

In [14]:
#Get specifice element. [r,c]
a[1,4]

np.int64(10)

In [15]:
# Negative Indexing . Last column will be -1
a[1,-2]

np.int64(12)

In [16]:
# Get a specific row . [r, :]]
a[1, :]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [17]:
# Get a specific column . [:, c]]
a[:, 3]

array([4, 9])

In [18]:
# Sllicing of array . [start:stop:jump]
# Start from index : stop before this index : jump
a[1, 1:4:]

array([7, 8, 9])

In [19]:
a[0, 1:4:]

array([2, 3, 4])

In [21]:
a[1, 1:-6:2]

array([7])

In [22]:
a[1,1:-1:2]

array([ 7,  9, 11])

Altering Data


In [25]:
a[0,7] = 10
print(a)

[[ 1  2  3  4  5  6  8 10]
 [ 6  7  8  9 10 11 12 13]]


In [26]:
a[:,-6] = 69
print(a)

[[ 1  2 69  4  5  6  8 10]
 [ 6  7 69  9 10 11 12 13]]


In [28]:
a[:,-7]= [6,9]
print(a)

[[ 1  6 69  4  5  6  8 10]
 [ 6  9 69  9 10 11 12 13]]
