In [2]:
import numpy as np

Target Array = 
[[1,1,1,1,1]
[1,0,0,0,1]
[1,0,9,0,1]
[1,0,0,0,1]
[1,1,1,1,1]]

In [16]:
a = np.ones([5,5])
a[1,1:4:] = 0
a[2,1:4:]= 0
a[2,2]=9
a[3,1:4:]= 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
O = np.ones([5,5])
z = np.zeros([3,3])
z[1,1]=9
O[1:4,1:4] = z
print (O)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful When copying array !!!!

In [3]:
b = np.array([1,2,3])
c = b
c  

array([1, 2, 3])

In [4]:
print(b)
print(c)
b[0] = 100
print(b)
print(c)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


To prevent this use copy function ...

d = b.copy()
d[0] = 1
d

In [8]:
d = b.copy()
d[0] = 1
print(d) 
print(b)

[1 2 3]
[100   2   3]
