In [1]:
import numpy as np

Target Array = 
[[1,1,1,1,1]
[1,0,0,0,1]
[1,0,9,0,1]
[1,0,0,0,1]
[1,1,1,1,1]]

In [16]:
a = np.ones([5,5])
a[1,1:4:] = 0
a[2,1:4:]= 0
a[2,2]=9
a[3,1:4:]= 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
O = np.ones([5,5])
z = np.zeros([3,3])
z[1,1]=9
O[1:4,1:4] = z
print (O)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
