In [2]:
import numpy as np

In [10]:
V1 = np.array([1,2,3])
V2 = np.array([5, 6, 7])
A = np.array([[1,2],[3,4]])
B = np.array([[6,7],[8,9]])

Matrix Multiplication :
Use @ or matmul() for matrix multiplication .

In [5]:
C = A @ B
C = np.matmul(A,B)
print(C)

[[22 25]
 [50 57]]


In [ ]:

# Dot Product :
# Use np.dot() .
dot = np.dot(V1,V2)
print(dot)

38


In [13]:
# Deteminant
I = np.identity(3)
print(np.linalg.det(I))

1.0


In [15]:
AT = A.T
print(AT)

[[1 3]
 [2 4]]


In [ ]:
# Inverse Matrix
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


Advanced Linear Algebra  

In [18]:
np.linalg.matrix_rank(A)

np.int64(2)

In [ ]:
# norm = It measures the Length of the vector 
v = np.array([3,4])
np.linalg.norm(v)

np.float64(5.0)

In [21]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Statistics

In [3]:
stats = np.array([[1,2,3],[6,7,8]])
stats

array([[1, 2, 3],
       [6, 7, 8]])

In [4]:
np.min(stats)

np.int64(1)

In [5]:
np.max(stats)

np.int64(8)

In [8]:
# axis = 0 means columnwise operation 
# axis = 1 means rowwise operation 
ax0 = np.mean(stats, axis = 0)
ax0

array([3.5, 4.5, 5.5])

In [11]:
ax1 = np.mean(stats, axis = 1)
ax1

array([2., 7.])