In [2]:
import numpy as np

In [10]:
V1 = np.array([1,2,3])
V2 = np.array([5, 6, 7])
A = np.array([[1,2],[3,4]])
B = np.array([[6,7],[8,9]])

Matrix Multiplication :
Use @ or matmul() for matrix multiplication .

In [5]:
C = A @ B
C = np.matmul(A,B)
print(C)

[[22 25]
 [50 57]]


In [ ]:

# Dot Product :
# Use np.dot() .
dot = np.dot(V1,V2)
print(dot)

38


In [13]:
# Deteminant
I = np.identity(3)
print(np.linalg.det(I))

1.0


In [15]:
AT = A.T
print(AT)

[[1 3]
 [2 4]]


In [ ]:
# Inverse Matrix
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


Advanced Linear Algebra  

In [18]:
np.linalg.matrix_rank(A)

np.int64(2)

In [ ]:
# norm = It measures the Length of the vector 
v = np.array([3,4])
np.linalg.norm(v)

np.float64(5.0)

In [21]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Reorganizing Array

In [15]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
after = before . reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Vertical Stacking Vectors 

In [22]:
VS1 = np.array([1,2,3])
VS2 = np.array([4,5,6])
result = np.vstack((VS1,VS2,VS1))
result 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

Horizontal Stack 

In [30]:
HS1 = np.ones([3,3])
HS2 = np.zeros([3,4])
print (HS1)
print (HS2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
Result = np.hstack((HS1,HS2))
Result

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])

Load Data from File

In [36]:
Filedata = np.genfromtxt("data.txt",delimiter=',',dtype = float)
Filedata.astype("int32") #Only copy
Filedata


array([[10., 20., 30.],
       [ 1.,  2.,  3.],
       [40., 50., 80.]])

Boolean Masking and Advanced Indexing 

In [37]:
Filedata >50

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [38]:
Filedata[Filedata > 50 ]

array([80.])

In [43]:
np.any(Filedata > 10 , axis = 0)

array([ True,  True,  True])

In [40]:
## You can index with a list in Numpy
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])