In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)
b = np.array([4,5,6,7,8])
print(a + b)
print(a ** 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 5  7  9 11 13]
[ 1  4  9 16 25]


In [5]:
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
