In [1]:
import numpy as np

In [2]:
stats = np.array([[1,2,3],[6,7,8]])
stats

array([[1, 2, 3],
       [6, 7, 8]])

In [3]:
np.min(stats)

np.int64(1)

In [4]:
np.max(stats)

np.int64(8)

In [5]:
# axis = 0 means columnwise operation 
# axis = 1 means rowwise operation 
ax0 = np.mean(stats, axis = 0)
ax0

array([3.5, 4.5, 5.5])

In [6]:
ax1 = np.mean(stats, axis = 1)
ax1

array([2., 7.])

In [7]:
np.sum(stats, axis=0)
np.sum(stats, axis=1)

array([ 6, 21])

In [8]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
after = before . reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Vertical Stacking Vectors 

In [10]:
VS1 = np.array([1,2,3])
VS2 = np.array([4,5,6])
result = np.vstack((VS1,VS2,VS1))
result 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

Horizontal Stack 

In [11]:
HS1 = np.ones([3,3])
HS2 = np.zeros([3,4])
print (HS1)
print (HS2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
Result = np.hstack((HS1,HS2))
Result

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])